# Generated by Django 4.2.7 on 2023-12-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_alter_envio_status_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tipo_envio',
            field=models.CharField(default='Próximas a vencer', max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
