# Generated by Django 4.2.7 on 2023-12-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='acao',
            field=models.CharField(default='Login', max_length=20, verbose_name='Acao'),
            preserve_default=False,
        ),
    ]
