# Generated by Django 4.2.7 on 2023-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_historico_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(max_length=100, verbose_name='Acao'),
        ),
    ]
