# Generated by Django 4.2.7 on 2023-12-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
