# Generated by Django 4.2.7 on 2024-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0011_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='emails',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
