# Generated by Django 4.2.7 on 2024-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0016_alter_envio_email_alter_modelo_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='contrato',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='email',
            field=models.CharField(max_length=1000, null=True, verbose_name='E-mail'),
        ),
    ]
